src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\OneToOne;

/**
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Une adresse pour un utilisateur.
     *
     * @OneToOne(targetEntity="User", inversedBy="address")
     * @JoinColumn(name="user_id", referencedColumnName="id",onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fullAddress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $route;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $locality;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adminstrativeArea;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postalCode;

    public function __toString()
    {
        if (is_null($this->fullAddress)) {
            return 'NULL';
        }

        return $this->fullAddress;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getFullAddress(): ?string
    {
        return $this->fullAddress;
    }

    public function setFullAddress(?string $fullAddress): self
    {
        $this->fullAddress = $fullAddress;

        return $this;
    }

    public function getRoute(): ?string
    {
        return $this->route;
    }

    public function setRoute(?string $route): self
    {
        $this->route = $route;

        return $this;
    }

    public function getLocality(): ?string
    {
        return $this->locality;
    }

    public function setLocality(?string $locality): self
    {
        $this->locality = $locality;

        return $this;
    }

    public function getAdminstrativeArea(): ?string
    {
        return $this->adminstrativeArea;
    }

    public function setAdminstrativeArea(?string $adminstrativeArea): self
    {
        $this->adminstrativeArea = $adminstrativeArea;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getLocation()
    {
        return $this->getLocality().', '.$this->getCountry();
    }
}

src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use App\Service\FileUploader;
use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ImagesRepository::class)
 */
class Images
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="images")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isVisible;

    /**
     * @ORM\ManyToOne(targetEntity=Gallery::class, inversedBy="images", fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="gallery_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     */
    private $gallery;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $position;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=ImageView::class, mappedBy="image", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $imageViews;

    /**
     * @ORM\OneToMany(targetEntity=ImageComment::class, mappedBy="image", orphanRemoval=true, cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $imageComments;

    /**
     * @ORM\OneToMany(targetEntity=ImageLike::class, mappedBy="image", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $imageLikes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $copyright;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isNSFW;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isHome;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isGallery;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $allowFavorites;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $allowLikes;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $allowComments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $size;

    /**
     * @ORM\Column(type="integer")
     */
    private $countView;

    public function __construct()
    {
        $this->imageViews = new ArrayCollection();
        $this->imageComments = new ArrayCollection();
        $this->imageLikes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->imageName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getImagePath()
    {
        return UploaderHelper::MEDIAS_USER.'/'.$this->user->getId().'/'.$this->gallery->getId().'/'.$this->getImageName();
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->isVisible;
    }

    public function setIsVisible(?bool $isVisible): self
    {
        $this->isVisible = $isVisible;

        return $this;
    }

    public function getGallery(): ?Gallery
    {
        return $this->gallery;
    }

    public function setGallery(?Gallery $gallery): self
    {
        $this->gallery = $gallery;

        return $this;
    }

    public function getThumbXs()
    {
        return $this->user->getId().'/'.$this->gallery->getId().'/thumbs/small_xs/'.$this->imageName;
    }

    public function getThumbMd()
    {
        return $this->user->getId().'/'.$this->gallery->getId().'/thumbs/small_md/'.$this->imageName;
    }

    public function getThumb()
    {
        return $this->user->getId().'/'.$this->gallery->getId().'/'.$this->imageName;
    }

    public function getCredentials()
    {
        $configAws = $this->imageHelper->getAws();

        return new FileUploader::$S3('files', $configAws);
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|ImageView[]
     */
    public function getImageViews(): Collection
    {
        return $this->imageViews;
    }

    public function addImageView(ImageView $imageView): self
    {
        if (!$this->imageViews->contains($imageView)) {
            $this->imageViews[] = $imageView;
            $imageView->setImage($this);
        }

        return $this;
    }

    public function removeImageView(ImageView $imageView): self
    {
        if ($this->imageViews->removeElement($imageView)) {
            // set the owning side to null (unless already changed)
            if ($imageView->getImage() === $this) {
                $imageView->setImage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ImageComment[]
     */
    public function getImageComments(): Collection
    {
        return $this->imageComments;
    }

    public function addImageComment(ImageComment $imageComment): self
    {
        if (!$this->imageComments->contains($imageComment)) {
            $this->imageComments[] = $imageComment;
            $imageComment->setImage($this);
        }

        return $this;
    }

    public function removeImageComment(ImageComment $imageComment): self
    {
        if ($this->imageComments->removeElement($imageComment)) {
            // set the owning side to null (unless already changed)
            if ($imageComment->getImage() === $this) {
                $imageComment->setImage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ImageLike[]
     */
    public function getImageLikes(): Collection
    {
        return $this->imageLikes;
    }

    public function addImageLike(ImageLike $imageLike): self
    {
        if (!$this->imageLikes->contains($imageLike)) {
            $this->imageLikes[] = $imageLike;
            $imageLike->setImage($this);
        }

        return $this;
    }

    public function removeImageLike(ImageLike $imageLike): self
    {
        if ($this->imageLikes->removeElement($imageLike)) {
            // set the owning side to null (unless already changed)
            if ($imageLike->getImage() === $this) {
                $imageLike->setImage(null);
            }
        }

        return $this;
    }

    public function getCopyright(): ?string
    {
        return $this->copyright;
    }

    public function setCopyright(?string $copyright): self
    {
        $this->copyright = $copyright;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getIsNSFW(): ?bool
    {
        return $this->isNSFW;
    }

    public function setIsNSFW(bool $isNSFW): self
    {
        $this->isNSFW = $isNSFW;

        return $this;
    }

    public function getIsHome(): ?bool
    {
        return $this->isHome;
    }

    public function setIsHome(bool $isHome): self
    {
        $this->isHome = $isHome;

        return $this;
    }

    public function getIsGallery(): ?bool
    {
        return $this->isGallery;
    }

    public function setIsGallery(bool $isGallery): self
    {
        $this->isGallery = $isGallery;

        return $this;
    }

    public function getAllowFavorites(): ?bool
    {
        return $this->allowFavorites;
    }

    public function setAllowFavorites(bool $allowFavorites): self
    {
        $this->allowFavorites = $allowFavorites;

        return $this;
    }

    public function getAllowLikes(): ?bool
    {
        return $this->allowLikes;
    }

    public function setAllowLikes(bool $allowLikes): self
    {
        $this->allowLikes = $allowLikes;

        return $this;
    }

templates/portfolio/tile-full-dark/base.html.twig
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title>
			{% block title %}
				{{ book.title }}
			{% endblock %}
		</title>
		<meta name="description" content="{% block description %} {{ book.description | raw }} {% endblock %}">
		{% if book.keywords %}
			<meta name="keywords" content="{{ book.keywords | raw }}">
		{% endif %}

		{% if not book.allowSeo %}
			<meta name="robots" content="noindex">
			<meta name="googlebot" content="noindex">
		{% else %}
			<meta name="robots" content="index, follow">
		{% endif %}
		<meta name="referrer" content="unsafe-url">
		<meta name="apple-mobile-web-app-capable" content="yes"/>
		<link rel="icon" type="image/ico" href="{{ asset('assets/img/favicon.png') }}">
		<link rel="canonical" href="{{ absolute_url('portfolio_index', { name : book.name }) }}"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		{% block stylesheets %}
			{{ encore_entry_link_tags('tile-full-dark') }}

			<!-- FONTS -->
			<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Raleway%3A400%2C100%2C300%2C500%2C600%2C700%2C800%2C900%7CRoboto%3A400%2C100%2C300%2C700%2C900%2C300italic%7CLibre+Baskerville%3A400%2C400i%2C700%7CLora%3A400%2C700%7CRoboto+Slab%3A400%2C300%2C700%2C100%7CUbuntu%3A400%2C300%2C500%2C700%7CDroid+Serif%3A400%2C400italic%2C700%2C700italic%7CGreat+Vibes%7CMontserrat%3A400%2C700%7CNoto+Sans%3A400%2C700%2C400italic%2C700italic%7COpen+Sans%26subset%3Dlatin%2Clatin-ext&#038;ver=1478770331' type='text/css' media='all'/>
		{% endblock %}

		<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

	</head>
	<body>
		{% for msg in app.session.flashbag.get('notice') %}
			<script>
				Swal.fire({
title: "{{ msg.title }}",
text: "{{ msg.message|raw }}",
icon: "{{ msg.type }}",
buttons: true,
dangerMode: false,
closeOnClickOutside: false,
closeOnEsc: false,
closeModal: true,
buttons: {
confirm: {
text: "Fermer",
value: true,
visible: true,
className: "btn-default text-center center",
closeModal: true
}
}
})
			</script>
		{% endfor %}
		<div class="main-wrapper">
			<div class="header">
				<div class="container no-padd">
					<div class="row">
						<div class="col-xs-12 no-padd-md no-padd-mob">
							<header class="top-menu">
								<a href="{{ path('portfolio_index', { name : book.name }) }}" class="hidden-xs logo">
									<img src="{{ avatar }}" width="85" class="img-circle img-responsive" alt="{{ book.user.fullname }}">
								</a>
								<h1 class="mt-0 font-20">{{ book.user.fullname }}</h1>
								<p class="hidden-xs title">{{ book.user.profession }}
									({{ book.user.experience}})
								</p>
								<p class="hidden-xs title">{{ book.user.address.location }}</p>
								<span class="hidden-xs line"></span>
								<a href="#" class="mob-nav">
									<i class="fa fa-bars"></i>
								</a>
								<nav id="topmenu">
									<ul id="menu-menu-1" class="menu">

										{% if book.user.isDemo %}
											<li class="menu-item {{ (app.request.get('_route') == 'template_preview_index') ? 'current-menu-item current_page_item current_page_parent':'' }}">
												<a href="{{ path('template_preview_index', { slug : design }) }}">Accueil</a>
											</li>
										{% else %}
											<li class="menu-item {{ (app.request.get('_route') == 'portfolio_index') ? 'current-menu-item current_page_item current_page_parent':'' }}">
												<a href="{{ path('portfolio_index', { name : book.name }) }}">Accueil</a>
											</li>
										{% endif %}

										{% if book.user.isDemo %}
											<li class="menu-item {{ (app.request.get('_route') == 'template_preview_about') ? 'current-menu-item current_page_item current_page_parent':'' }}">
												<a href="{{ path('template_preview_about', { slug : design }) }}">À propos</a>
											</li>
										{% else %}
											<li class="menu-item {{ (app.request.get('_route') == 'portfolio_about') ? 'current-menu-item current_page_item current_page_parent':'' }}">
												<a href="{{ path('portfolio_about', { name : book.name }) }}">À propos</a>
											</li>
										{% endif %}

										{% if book.user.isDemo %}
											<li class="menu-item menu-item-has-children {{ (app.request.get('_route') == 'template_preview_galleries' or app.request.get('_route') == 'template_preview_gallery_show' ) ? 'current-menu-item current_page_item current_page_parent':'' }}">
												<a href="{{ path('template_preview_galleries', { slug : design }) }}">Galeries</a>
												{% if galleries %}
													<ul class="sub-menu">
														{% for gallery in galleries %}
															<li class="menu-item ">
																<a href="{{ path('template_preview_gallery_show', { slug_design : design, slug : gallery.list.getSlug() }) }}">{{ gallery.list.getName() }}</a>
															</li>
														{% endfor %}
													</ul>
												{% endif %}
											</li>
										{% else %}
											<li class="menu-item menu-item-has-children {{ (app.request.get('_route') == 'portfolio_galleries' or app.request.get('_route') == " portfolio_gallery_show" ) ? 'current-menu-item current_page_item current_page_parent':'' }}">
												<a href="{{ path('portfolio_galleries', { name : book.name }) }}">Galeries</a>
												{% if galleries %}
													<ul class="sub-menu">
														{% for gallery in galleries %}
															<li class="menu-item ">
																<a href="{{ path('portfolio_gallery_show', { name : book.name, slug : gallery.list.getSlug() }) }}">{{ gallery.list.getName() }}</a>
															</li>
														{% endfor %}
													</ul>
												{% endif %}
											</li>
										{% endif %}

										{% if book.user.videos | length > 0 %}
											{% if book.user.isDemo %}
												<li class="menu-item {{ (app.request.get('_route') == 'template_preview_video') ? 'current-menu-item current_page_item current_page_parent':'' }}">
													<a href="{{ path('template_preview_video', { slug : design }) }}">Vidéos</a>
												</li>
											{% else %}
												<li class="menu-item {{ (app.request.get('_route') == 'portfolio_video') ? 'current-menu-item current_page_item current_page_parent':'' }}">
													<a href="{{ path('portfolio_video', { name : book.name }) }}">Vidéos</a>
												</li>
											{% endif %}
										{% endif %}

										{% if book.allowComments %}
											{% if book.user.isDemo %}
												<li class="menu-item {{ (app.request.get('_route') == 'template_preview_guestbook') ? 'current-menu-item current_page_item current_page_parent':'' }}">
													<a href="{{ path('template_preview_guestbook', { slug : design }) }}">Commentaires</a>
												</li>
											{% else %}
												<li class="menu-item {{ (app.request.get('_route') == 'portfolio_guestbook') ? 'current-menu-item current_page_item current_page_parent':'' }}">
													<a href="{{ path('portfolio_guestbook', { name : book.name }) }}">Commentaires</a>
												</li>
											{% endif %}
										{% endif %}

										{% if pages %}
											{% for page in pages %}
												{% if book.user.isDemo %}
													<li class="menu-item {{ (app.request.get('_route') == 'template_preview_page' and app.request.get('slug') == page.getSlug() ) ? 'current-menu-item current_page_item current_page_parent':'' }}">
														<a href="{{ path('template_preview_page', { slug_page : design, slug : page.getSlug() }) }}">{{ page.getTitle }}</a>
													</li>
												{% else %}

													<li class="menu-item {{ (app.request.get('_route') == 'portfolio_page' and app.request.get('slug') == page.getSlug() ) ? 'current-menu-item current_page_item current_page_parent':'' }}">
														<a href="{{ path('portfolio_page', { name : book.name, slug : page.getSlug() }) }}">{{ page.getTitle }}</a>
													</li>
												{% endif %}
											{% endfor %}
										{% endif %}

										{% if book.showContact %}
											{% if book.user.isDemo %}
												<li class="menu-item {{ (app.request.get('_route') == 'template_preview_contact') ? 'current-menu-item current_page_item current_page_parent':'' }}">
													<a href="{{ path('template_preview_contact', { slug : design }) }}">Contact</a>
												</li>
											{% else %}

												<li class="menu-item {{ (app.request.get('_route') == 'portfolio_contact') ? 'current-menu-item current_page_item current_page_parent':'' }}">
													<a href="{{ path('portfolio_contact', { name : book.name }) }}">Contact</a>
												</li>
											{% endif %}
										{% endif %}
									</ul>

								</nav>
							</header>
						</div>
					</div>
				</div>
			</div>
			{% block body %}{% endblock %}
			<footer id="footer">
				{% block footer %}
					<div class="container no-padd-md">
						<div class="copyright">
							Copyright
							{{ "now"|date("Y") }}
							<a href="{{ path('index') }}" target="_blank">Bookfolio</a>
							- Tous droits réservés.<br>
							Book crée le
							{{ book.user.createdAt | format_datetime(locale='fr', pattern="dd MMMM YYYY") }}
							{% if book.showVisitorCounter %}-
								{{ book.user.statistics | length }}
								{{ (book.user.statistics | length > 1) ? 'visites':'visite'}}
							{% endif %}

							{% if not book.user.isDemo %}
								-
								{% if not iamFollow %}
									<a href="{{ path('portfolio_add_follow', { name : book.name }) }}">S'abonner</a>
								{% else %}
									<a href="{{ path('portfolio_remove_follow', { name : book.name }) }}">Se désabonner</a>
								{% endif %}
							{% endif %}
						</div>
						<div class="social-links">

							{% if book.user.social.instagram %}
								<a href="{{ book.user.social.instagram }}" target="_blank">
									<i class="fa fa-instagram"></i>
								</a>
							{% endif %}

							{% if book.user.social.facebook %}
								<a href="{{ book.user.social.facebook }}" target="_blank">
									<i class="fa fa-facebook"></i>
								</a>
							{% endif %}

							{% if book.user.social.twitter %}
								<a href="{{ book.user.social.twitter }}" target="_blank">
									<i class="fa fa-twitter"></i>
								</a>
							{% endif %}

							{% if book.user.social.linkedin %}
								<a href="{{ book.user.social.linkedin }}" target="_blank">
									<i class="fa fa-linkedin"></i>
								</a>
							{% endif %}

							{% if book.user.social.tumblr %}
								<a href="{{ book.user.social.tumblr }}" target="_blank">
									<i class="fa fa-tumblr"></i>
								</a>
							{% endif %}

							{% if book.user.social.pinterest %}
								<a href="{{ book.user.social.pinterest }}" target="_blank">
									<i class="fa fa-pinterest"></i>
								</a>
							{% endif %}

							{% if book.user.social.skype %}
								<a href="{{ book.user.social.skype }}" target="_blank">
									<i class="fa fa-skype"></i>
								</a>
							{% endif %}

						</div>
					</div>
				{% endblock %}
			</footer>

		</div>
		{% block javascripts %}
			{{ encore_entry_script_tags('tile-full-dark') }}
			{% if book.codeAnalytics %}
				<script>
					(function (i, s, o, g, r, a, m) {
i['GoogleAnalyticsObject'] = r;
i[r] = i[r] || function () {
(i[r].q = i[r].q || []).push(arguments)
},
i[r].l = 1 * new Date();
a = s.createElement(o),
m = s.getElementsByTagName(o)[0];
a.async = 1;
a.src = g;
m.parentNode.insertBefore(a, m)
})(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

ga('create', '{{ book.codeAnalytics }}', 'auto');
ga('send', 'pageview');
				</script>
			{% else %}
				<script>
					(function (i, s, o, g, r, a, m) {
i['GoogleAnalyticsObject'] = r;
i[r] = i[r] || function () {
(i[r].q = i[r].q || []).push(arguments)
},
i[r].l = 1 * new Date();
a = s.createElement(o),
m = s.getElementsByTagName(o)[0];
a.async = 1;
a.src = g;
m.parentNode.insertBefore(a, m)
})(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

ga('create', 'UA-79500816-1', 'auto');
ga('create', 'UA-79500816-1', {cookieDomain: '.book-folio.fr'});
ga('send', 'pageview');
				</script>
			{% endif %}

			<script type="text/javascript">
				var name = '{{ book.name }}'
			</script>
		{% endblock %}
	</body>
</html>

templates/portfolio/tile-full-dark/galleries.html.twig
{% extends 'portfolio/' ~ design ~'/base.html.twig' %}
{% block title %}
	{% if book.getTitle() %}
		Galeries -
		{{ book.getTitle() }}
	{% else %}
		Galeries -
		{{ book.user.getFullname() }}
	{% endif %}
{% endblock %}

{% block description %}
	Galeries -
	{{ book.getDescription() | raw }}
	-
	{{ book.user.getFullname() }}
{% endblock %}


{% block body %}
	<div class="container clearfix no-padd portfolio-single-content margin-lg-30b ">
		<div class="row">
			{% if galleries | length > 0 %}
				<div class="portfolio-wrapper">
					<div class="portfolio simple col-4 clearfix no-padd" data-space="15">
						<div class="col-sm-12">
							<div class="wpb_wrapper">
								{% for gallery in galleries %}
									<div class="item">
										<a href="{{ path('portfolio_gallery_show', { name : book.name, slug : gallery.list.getSlug() }) }}" class="item-link gridrotate-alb">
											<div class="item-img">
												<div class="images-one">
													{% if gallery.list.isProtect %}
														<img src="{{ gallery.list.getLocked() }}" alt="" class="s-img-switch">
													{% else %}
														{% if gallery.list.coverImage %}
															<img src="{{ gallery.list.coverImage.imagePath | imagine_filter('thumbnail_card') }}" alt="{{ gallery.list.getName() }}" class="s-img-switch">
														{% else %}
															<img src="{{ ((gallery.list.getLastImage() != null) ? gallery.cover.imagePath | imagine_filter('thumbnail_card') : gallery.list.getNoThumb() ) }}" alt="" class="s-img-switch">
														{% endif %}
													{% endif %}
												</div>
											</div>
											<div class="item-overlay">
												<h5>{{ gallery.list.getName() }}</h5>
											</div>
										</a>
									</div>
								{% endfor %}

							</div>
						</div>
					</div>
				</div>
			{% else %}
				<div class="col-12">
					<div class="alert alert-warning text-center" role="alert">Aucune galerie public pour l'instant.</div>
				</div>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/portfolio/tile-full-dark/index.html.twig
{% extends 'portfolio/' ~ design ~'/base.html.twig' %}

{% block title %}
	{% if book.title %}
		{{ book.title }}
	{% else %}
		{{ book.user.fullname }}
		- Accueil
	{% endif %}
{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div id="tileFullLightImagesHome"></div>
			</div>
		</div>
		<div class="row">
			{% if showGallery %}
				{% include 'portfolio/partial/link_gallery.html.twig' with {'book': book,'col':'col-lg-4 col-lg-offset-4'} %}
			{% endif %}
		</div>
	</div>
{% endblock %}